# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Divya Wadhwa Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Divya Wadhwa
headline: Mechanical Engineering Undergraduate Student
description: |

  🛠️ Python, MATLAB, and Hands-on Engineering Projects<br>

  💡 Welcome to my portfolio! This repository shows a selection of engineering and computing projects I have developed during my time at Purdue Universitry.<br>

  🚀 Check out individual folders for detailed READMEs, descriptions, images, live demos, visual outputs, and source code.<br>



# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/IMG_1780.jpg


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
resume: ./assets/resume/Resume_Divya_V_Wadhwa.pdf


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin:  # https://www.linkedin.com/in/divyavwadhwa/ 
  github:   # https://github.com/divya-wadhwa 
  stackoverflow:      # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: Excel
    tools:
    - IF
    - VLOOKUP
    - INDEX-MATCH
    - Conditional Formatting
    - Pivot Tables
    - Chart Generation
    - Logical Operators
    - Custom Formulae
  - category: Python
    tools:
    - Pandas
    - matplotlib
    - Conditionals
    - Loops
    - File I/O
    - Plotting 
    - Modular Coding
  - category: MATLAB
    tools:
    - Scripts
    - Plotting
    - Logical/relational operators 
  - category: Mechanical Design & Troubleshooting
    tools:
    - Pneumatic systems
    - Frame alignment
    - Custom bracket fabrication
    - Sensor integration
    - CAD-free assembly validation
  - category: Systems Testing & Failure Analysis
    tools:
    - FMEA 
    - Compliance with medical safety standards
    - Multimeter diagnostics
    - Signal amplification (op-amp)
    - Stress/load evaluation
    - Error tracing
    - Safety validation

# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   https://formspree.io/f/mrblqwkl


# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # tech-inspired dark theme
  text: "#d0d0d0"          # light gray text for contrast on dark bg
  border: "#44475a"        # muted dark slate border
  link: "#8be9fd"          # bright cyan for links (tech vibe)
  highlight: "#ff79c6"     # vibrant pink/purple highlight
  background: "#1e1f29"    # very dark blue/gray background
  light_background: "#2a2d3e" # slightly lighter dark bg for contrast areas




#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
